image:
  backend:
    repository: 840577818615.dkr.ecr.us-east-1.amazonaws.com/bootcamp1-app/backend
    tag: "49239445ed047f569b81029d8af5422ac214c569"
  frontend:
    repository: 840577818615.dkr.ecr.us-east-1.amazonaws.com/bootcamp1-app/frontend
    tag: "49239445ed047f569b81029d8af5422ac214c569"
backend:
  replicas: 2
frontend:
  replicas: 2
ingress:
  host: app.aws.vijaiveerapandian.com
  certificateArn: arn:aws:acm:us-east-1:840577818615:certificate/d5f6fe91-d0d7-4611-8be4-d7324ebfb45a
